-- MySQL Script generated by MySQL Workbench
-- Sun Sep  7 14:49:31 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
DROP DATABASE IF EXISTS `MundoGPUBD`;

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema MundoGPUBD
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema MundoGPUBD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MundoGPUBD` DEFAULT CHARACTER SET utf8mb3 ;
USE `MundoGPUBD` ;

-- -----------------------------------------------------
-- Table `MundoGPUBD`.`Nivel_Academico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MundoGPUBD`.`Nivel_Academico` (
  `idNivel` INT NOT NULL AUTO_INCREMENT,
  `Nivel` VARCHAR(50) NOT NULL,
  `Institucion` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`idNivel`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `MundoGPUBD`.`Generales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MundoGPUBD`.`Generales` (
  `idGeneral` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `apellido` VARCHAR(50) NOT NULL,
  `sexo` ENUM('M', 'F') NOT NULL,
  `Nivel_Academico_idNivel` INT NOT NULL,
  PRIMARY KEY (`idGeneral`),
  INDEX `fk_Generales_Nivel_Academico1_idx` (`Nivel_Academico_idNivel` ASC) VISIBLE,
  CONSTRAINT `fk_Generales_Nivel_Academico1`
    FOREIGN KEY (`Nivel_Academico_idNivel`)
    REFERENCES `MundoGPUBD`.`Nivel_Academico` (`idNivel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `MundoGPUBD`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MundoGPUBD`.`user` (
  `idUSER` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(16) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `rol` ENUM('ADMIN', 'ENCARGADO', 'EMPLEADO') NOT NULL,
  `Generales_idGeneral` INT NOT NULL,
  PRIMARY KEY (`idUSER`),
  UNIQUE INDEX `UC_User_Username` (`username` ASC) VISIBLE,
  INDEX `fk_user_Generales_idx` (`Generales_idGeneral` ASC) VISIBLE,
  CONSTRAINT `fk_user_Generales`
    FOREIGN KEY (`Generales_idGeneral`)
    REFERENCES `MundoGPUBD`.`Generales` (`idGeneral`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `MundoGPUBD`.`Proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MundoGPUBD`.`Proveedores` (
  `idProveedor` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(100) NOT NULL,
  `Direccion` VARCHAR(255) NULL DEFAULT NULL,
  `Telefono` VARCHAR(20) NULL DEFAULT NULL,
  `Email` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`idProveedor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `MundoGPUBD`.`GPU`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MundoGPUBD`.`GPU` (
  `idGPU` INT NOT NULL AUTO_INCREMENT,
  `Marca` VARCHAR(50) NOT NULL,
  `Modelo` VARCHAR(100) NOT NULL,
  `VRAM` VARCHAR(50) NOT NULL,
  `NucleosCuda` INT NOT NULL,
  `RayTracing` TINYINT(1) NOT NULL,
  `Imagen` VARCHAR(255) NOT NULL,
  `Precio` DECIMAL(10,2) NOT NULL,
  `Proveedores_idProveedor` INT NOT NULL,
  PRIMARY KEY (`idGPU`),
  INDEX `fk_GPU_Proveedores1_idx` (`Proveedores_idProveedor` ASC) VISIBLE,
  CONSTRAINT `fk_GPU_Proveedores1`
    FOREIGN KEY (`Proveedores_idProveedor`)
    REFERENCES `MundoGPUBD`.`Proveedores` (`idProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


INSERT INTO Nivel_Academico (Nivel, Institucion)
VALUES ('Licenciatura', 'Universidad Nacional');

SELECT * FROM Nivel_Academico;

INSERT INTO Generales (nombre, apellido, sexo, Nivel_Academico_idNivel)
VALUES ('Admin', 'Admin', 'M', 1);  -- Asumiendo que idNivel del nivel insertado es 1

SELECT * FROM Generales;

INSERT INTO user (username, password, rol, Generales_idGeneral)
VALUES ('Admin', 'Admin', 'ADMIN', 3);  -- Asumiendo que idGeneral del admin es 1

SELECT * FROM user;

-- Insertar proveedores
INSERT INTO `MundoGPUBD`.`Proveedores` (`Nombre`, `Direccion`, `Telefono`, `Email`) VALUES
('NVIDIA Corp', '2788 San Tomas Expressway, Santa Clara, CA, USA', '+1-408-486-2000', 'contact@nvidia.com'),
('AMD Inc', '2485 Augustine Dr, Santa Clara, CA, USA', '+1-408-749-4000', 'info@amd.com'),
('EVGA Corporation', '6500 Kaiser Blvd, Fremont, CA, USA', '+1-510-657-4400', 'support@evga.com'),
('ASUS', 'No. 15, Li-Te Rd., Beitou, Taipei, Taiwan', '+886-2-2894-3447', 'sales@asus.com'),
('MSI', 'No.69, Lide St., New Taipei City, Taiwan', '+886-2-3234-5599', 'contact@msi.com');

-- Insertar GPUs
INSERT INTO `MundoGPUBD`.`GPU` (`Marca`, `Modelo`, `VRAM`, `NucleosCuda`, `RayTracing`, `Imagen`, `Precio`, `Proveedores_idProveedor`) VALUES
('NVIDIA', 'GeForce RTX 4090', '24 GB GDDR6X', 16384, 1, 'https://m.media-amazon.com/images/I/51c1zFDNVmL.__AC_SY300_SX300_QL70_FMwebp_.jpg', 1599.99, 1),
('NVIDIA', 'GeForce RTX 4080', '16 GB GDDR6X', 9728, 1, 'https://m.media-amazon.com/images/I/71m9FJCubXL._AC_SX466_.jpg', 1199.99, 1),
('AMD', 'Radeon RX 7900 XTX', '24 GB GDDR6', 6144, 1, 'https://www.gigabyte.com/FileUpload/Global/KeyFeature/2235/innergigabyteimages/kfimg.png', 999.99, 2),
('AMD', 'Radeon RX 7800 XT', '16 GB GDDR6', 3840, 1, 'https://static.gigabyte.com/StaticFile/Image/Global/fd0cf67f7b5bfe8409e941efad36cc03/Product/38874/png/1000', 699.99, 2),
('EVGA', 'GeForce RTX 4070 Ti', '12 GB GDDR6X', 7680, 1, 'https://postperspective.com/wp-content/uploads/2023/01/ezgif.com-gif-maker4.png', 799.99, 3),
('ASUS', 'ROG Strix RTX 4080', '16 GB GDDR6X', 9728, 1, 'https://www.noticias3d.com/articulos/202403/asus-rog-strix-geforce-rtx-4080-super/imagenes/asus-rog-strix-geforce-rtx-4080-super-frontal.jpg', 1249.99, 4),
('MSI', 'Suprim X RTX 4090', '24 GB GDDR6X', 16384, 1, 'https://asset.msi.com/resize/image/global/product/product_16638235057f0a6b07c9a45c417972d5209c5a16b5.png62405b38c58fe0f07fcef2367d8a9ba1/600.png', 1649.99, 5);

INSERT INTO `MundoGPUBD`.`GPU` (`Marca`, `Modelo`, `VRAM`, `NucleosCuda`, `RayTracing`, `Imagen`, `Precio`, `Proveedores_idProveedor`) VALUES
('NVIDIA', 'GeForce RTX 4090', '24 GB GDDR6X', 16384, 1, 'https://m.media-amazon.com/images/I/51c1zFDNVmL.__AC_SY300_SX300_QL70_FMwebp_.jpg', 1599.99, 1);


use mundogpubd;
INSERT INTO Nivel_Academico (Nivel, Institucion)
VALUES ('Sin nivel', 'N/A');

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

drop database mundogpubd;

show databases;
